### ISSUE TITLE
Implementation of 'Divide & Conquer' feature

### ISSUE THREAD

**Issue by Tran-Antoine** [Tran-Antoine/algo-companion#2]
I figured it'd be useful to start off by listing the questions we need to address before getting started.

> What are the possible "inputs" of the problem ? Is it general enough to only work with lists of numbers? Should we do something more abstract that gives more freedom?

~~I personally think that lists of numbers are good enough for now, we'll see later if we need more flexibility~~

***

> How does the user provide the specs of their algorithm?

The idea I had was to have multiple input boxes:
- The recurrence relation for the total cost (so we can use the master theorem to instantly compute the complexity)
- A minimalist python script with global variables available (input and size basically) that specifies the division procedure. Maybe we can have "default" settings such as "evenly dividing in N pieces", where N could be infered from the recurrence relation
- A minimalist python script with global variables available (input1, input2, ..., size) that specifies the combining procedure. Default could be concatenation

***

> What kind of animation would be useful?

I think it would be nice to show the base input, then divide it until we reach the base case, solve the best case then regroup the pieces. It's all a D&C algorithm always does as far as I know, I don't know if there are additional features that would be interesting to add. Should we go for a step-by-step animation where the user decides when to go to the next step? Should the user be able to interact in any way to maybe modify the input, correct a part of the animation on the fly, etc?
Maybe a cool feature would be to allow the user to "mark" steps in the combining procedure, so the animation could highlight those steps. For instance, if the user writes a merge-sort, they could do something like `mark(chosen_number)` (where `chosen_number` is the current smallest number out of the two lists) and that would highlight that number on the animation. So calling `mark` would both pause the animation and highlight a certain number

***

> Does initial input need to be specified?

I think it would be nice to be able to choose between "random numbers" or a specific list. It can be useful for the user to test specific inputs so allowing them to enter them is important, but it's also practical to be able to run it with multiple random inputs to see if it works

***

> Can we add a feature to instantly test if the algorithm ran perfectly?

We could maybe have an input box that defines a *verifier*, an algorithmic procedure that checks that the output is correct, that would enable fast forwarding the visualization in some cases, which could make the user save some time if their algorithm is correct

**Comment by Tran-Antoine** [comment]
Actually, now that I think about it, it may be interesting to allow multiple types of data structures (not just lists) such as sets, matrices, binary trees, etc. But only things that we can easily visualize in the simulation

**Comment by Tran-Antoine** [comment]
Also, it would be interesting to have a "save" button that saves the specs somewhere so the user can import it next time they use the tool

**Comment by maxeliot** [comment]
Seems good to me! 👍
