### ISSUE TITLE
Definition of the protocol for sending simulation results through sockets

### ISSUE THREAD

**Issue by Tran-Antoine** [Tran-Antoine/algo-companion#5]
After a quick discussion with some developers, we concluded that sending simulation results through the local network via sockets was the way to go. So we need some protocol for sending and receiving messages.

**Comment by Tran-Antoine** [comment]
I suggest the following 4 messages:

`REGISTER <id>`
`DIVIDE <id> <depth> <index> <output1> <output2> ... <hl1> <hl2> ...`
`COMBINE <id> <depth> <index> <output> <hl1> <hl2> ...`
`DONE <id>`

where:
- `id` is the identifier of the input
- `depth` is the layer at which the calculation occured
- `index` is the index of the input (in case of division) or the index of the output (in case of combining)
- `output` is the output of the combining process
- `output1, ...` are the outputs of the division process
- `hl1, ...` are the in-between steps where certain values need to be highlighted

**Comment by maxeliot** [comment]
To serialize the REGISTER/DIVIDE/COMBINE/DONE message objects, I think we can simply transform each attribute of the class into a String (with a function that is invertible), and then concatenate them (with a separator in between). For deserialization we simply do the inverse procedure.

**Comment by maxeliot** [comment]
More precisely, we transform each class attribute of the message class (`id`, `depth`, ...)
to a string and concatenate them in a string with forward slash `/` as separator. 
Primitive type attributes transformations are trivial (in scala use String.valueOf method).
For Lists of primitives we seperate each value by a comma `,` and prefix/suffix with parantheses (for example `[0, 5, 10]` would become `"(0,5,10)"`.
For the output attribute (type InputType) (COMBINE Message) we transform the single attribute of the corresponding class (a list of ints for IList, ...)

To be done : define transformation for `BinaryTree[Int]`

**Comment by Tran-Antoine** [comment]
Works for me. I'll use this protocol for the python implementation.

**Comment by Tran-Antoine** [comment]
I think it's ok to close this now. We may reopen it when we want to add support for binary trees
